### ISSUE TITLE
Why casting version number to a date

### ISSUE THREAD

**Issue by jaxunet** [cloudbase/powershell-yaml#10]
Hi there,
Could you please help me solve a problem with automatic casting version number to a date format?

I have yaml file and I read it using your library.

Now here is example of yaml file (properly formatted):
`#Software Config`
`service:`
 ` version: 7.9.67-1`
`  developer:`
 `   licence: test`

And now after loading - this file version is cast to a date format.
7.9.67-1 is now 09/07/1967 02:00:00
(Also hour is strange, should be 01 but is 02 --> when the second number is bigger than 3 then hour is +1)

When number doesn't match to a date format then version is fine eg: 57.23.3-1

Did you face this problem?

How to avid casting?
I tried with "", '' and it doesn't help.

**Comment by gabriel-samfira** [comment]
It's a side effect of trying to be to smart for one's own good. The idea behind the conversion was to be able to serialize and unserialize date objects. The problem is that powershell allows weak conversion. 

The goal was this:

```powershell
PS /tmp/mozilla_gabriel0> get-date                                                        

Friday, July 21, 2017 5:12:38 PM


PS /tmp/mozilla_gabriel0> [DateTime]"Friday, July 21, 2017 5:12:38 PM"                    

Friday, July 21, 2017 5:12:38 PM
```

The problem is this:

```powershell
PS /tmp/mozilla_gabriel0> [dateTime]1                                                     

Monday, January 1, 0001 12:00:00 AM
```

I will probably remove the ```[DateTime]``` conversion.

**Comment by gabriel-samfira** [comment]
Can you try out the latest commit available here: https://github.com/cloudbase/powershell-yaml/commit/25f0e6d00a34b8d51af1df30cc304fab521639fa ? It should leave your version number as a string. Note, you will have to do any conversion yourself.

**Comment by jaxunet** [comment]
Hi Gabriel,
Thanks for feedback and work.
I will try it tomorrow and I will let you know results.

**Comment by gabriel-samfira** [comment]
Hi @jaxunet Any updates? Can I close this issue?

**Comment by jaxunet** [comment]
Hi Gabriel,
Apologies for late reply. 

Just tried this now.
I imported module. So new function is available. I loaded config file into variable $config.
Now when calling **convertfrom-yaml $config** then I am getting this error:

`New-Object : Exception calling ".ctor" with "1" argument(s): "Culture is not supported.
Parameter name: name
invariant is an invalid culture identifier."
At C:\tmp\powershell-yaml\powershell-yaml.psm1:41 char:20
+ ...   $culture = New-Object System.Globalization.CultureInfo("invariant")
    + CategoryInfo          : InvalidOperation: (:) [New-Object], MethodInvocationException
    + FullyQualifiedErrorId : ConstructorInvokedThrowException,Microsoft.PowerShell.Commands.NewObjectCommand`

Do you think I missed something or there is another problem?

I tried modified 41 line  to ...CultureInfo.InvariantCulture, but doesn't help. (https://msdn.microsoft.com/en-gb/library/system.globalization.cultureinfo.invariantculture(v=vs.110).aspx)

Please advise

**Comment by gabriel-samfira** [comment]
can you tell me what powershell version you're using? (I need to test on more versions of powershell before I push next time)

**Comment by gabriel-samfira** [comment]
Thanks! that helps. I'll do an update later today, and pink you back.

**Comment by gabriel-samfira** [comment]
Hi @jaxunet 

This issue should be fixed by: https://github.com/cloudbase/powershell-yaml/pull/12

Could you give it another try? if it works for you, I will update it in the gallery.

**Comment by jaxunet** [comment]
Hi @gabriel-samfira 
I just tested it and seems to work fine. 
Many thanks for this fix.
