### ISSUE TITLE
Add `Test-Yaml` cmdlet

### ISSUE THREAD

**Issue by iRon7** [cloudbase/powershell-yaml#105]
Similar to the [`Test-Json`](https://learn.microsoft.com/powershell/module/microsoft.powershell.utility/test-json) cmdlet, it would be nice to have a schema validator.
See also [Yaml schema Validation powershell](https://stackoverflow.com/questions/57253836/yaml-schema-validation-powershell)

**Comment by gabriel-samfira** [comment]
Hi @iRon7 

My apologies for the embarrassingly late answer.

There doesn't seem to be a good Yaml Schema library out there. Most articles I could find suggested to use JSON schema validation to get most of the way there. There is a draft that describes addons to json schema validation that is supposed to extend it to validate YAML as well, but it seems to be a draft.

That being said, you can probably get the desired result with something like this:

Define the schema:

```powershell
$ContentsOfTheSchema = @"                                                                               
{
  "type": "object",                                
  "properties": {  
    "test": {    
      "type": "string",
      "description": "test is string"
    },                               
    "intTest": {
      "type": "integer",
      "description": "test is int"
    }                             
  }, 
  "additionalProperties": false
}                              
"@
```

Define the Yaml:

```powershell
$YamlContents = @"                                                                                      
---                       
test: "stringTest"
intTest: !!int "11"
"@
```

Run the validation:

```powershell
PS /home/gabriel> ConvertFrom-Yaml $YamlContents | ConvertTo-Yaml -JsonCompatible | Test-Json -Schema $ContentsOfTheSchema
True
```

If we change the Yaml and remove the `!!int` tag, turning that `intTest` field into a string, we should get an error:

```powershell
PS /home/gabriel> $YamlContents = @"                                                                                      
>> ---
>> test: "stringTest"
>> intTest: "11"      
>> "@
PS /home/gabriel> ConvertFrom-Yaml $YamlContents | ConvertTo-Yaml -JsonCompatible | Test-Json -Schema $ContentsOfTheSchema
Test-Json: The JSON is not valid with the schema: Value is "string" but should be "integer" at '/intTest'
False
```

**Comment by iRon7** [comment]
Thanks for the answer and suggestion

**Comment by iRon7** [comment]
FYI,: I have created my own object tester cmdlet that is independent of the source notation.

```PowerShell
$Object = @{ # ConvertFrom-Yaml $YamlContents | ConvertTo-Expression
    intTest = 11
    test = 'stringTest'
}
```

```PowerShell
$Schema = @{
  test = @{    
    '@description' = "test is string"
    '@type' = "string"
  }
  intTest = @{
    '@description' = "test is int"
    '@type' = "int"
  }                             
}                              
```

```PowerShell
Install-Module -Name ObjectGraphTools -AllowPrerelease
$Object | Test-Object $Schema
```

As the module is completely written in PowerShell it performs less that e.g. `Test-Json`, but I think it has some nice features which give you more concise testing capabilities. For details see the `ObjectGraphTools` documentation along with the [`SchemaObject` document](https://github.com/iRon7/ObjectGraphTools/blob/main/Docs/SchemaObject.md)
