### ISSUE TITLE
Class with PSCustomObject ConvertTo-Yaml fail

### ISSUE THREAD

**Issue by ili101** [cloudbase/powershell-yaml#106]
```powershell
$PsO = [PSCustomObject]@{
    Name = 'Value'
}

class TestClass {
    [PSCustomObject]$PsO
    [string]$Ok
}
$Class = [TestClass]@{
    PsO = $PsO
    Ok  = 'Yes'
}
$Class | ConvertTo-Yaml
# Too much recursion when traversing the object graph.
```

**Comment by gabriel-samfira** [comment]
Yes, sadly YamlDotNet doesn't serialize ```PSCustomObject``` well. We actually convert it internally before passing it to ```YamlDotNet```. We didn't yet add a case for classes, so a class is sent to ```YamlDotNet``` as is, without any conversion.

This is where the error comes from. Need to add a case for classes. Don't have the time for it right now, but will get to it as soon as I can.

**Comment by gabriel-samfira** [comment]
So, after an embarrassingly long amount of time, I had a chance to look at this and hopefully addressed it properly. If you're still interested, there is a PR (#135) that should fix this.

**Comment by gabriel-samfira** [comment]
Pushed a pre-release to powershell gallery:

```powershell
Install-Module -Name powershell-yaml -AllowPrerelease -Version 0.4.8-rc2 -Force
```
