### ISSUE TITLE
Copyright is out of date

### ISSUE THREAD

**Issue by lboening** [cloudbase/powershell-yaml#107]
I noticed the copyright info is out of date (it would seem). I see year 2016. Perhaps you could update to year 2023?  This caused some mental stress as I wondered if this product was established in 2016 and then abandoned.

**Comment by gabriel-samfira** [comment]
Hi @lboening !

The project is still maintained. My apologies for the stress! I need to ask internally first, but I think I'll just remove the year and leave the rest.

Gabriel

**Comment by gabriel-samfira** [comment]
Fixed by https://github.com/cloudbase/powershell-yaml/commit/df1cf8eaf778a36b20d1410996def07d238f2831
