### ISSUE TITLE
Cannot find type [YamlDotNet.Core.Parser]

### ISSUE THREAD

**Issue by stottler** [cloudbase/powershell-yaml#122]
Hello,

The module was working yesterday when I left my office. I changed nothing and am now getting this error.

New-Object: Cannot find type [YamlDotNet.Core.Parser]: verify that the assembly containing this type is loaded.
New-Object: Cannot find type [YamlDotNet.RepresentationModel.YamlStream]: verify that the assembly containing this type is loaded.
InvalidOperation: Unable to find type [YamlDotNet.Core.IParser].

Example code where it's breaking.
$yamlfile = Get-Content -Path "config.yaml"
$yaml = ConvertFrom-Yaml $yamlfile

I'm not sure what broke.

**Comment by gabriel-samfira** [comment]
This can only happen if you already had another YamlDotNet assembly loaded in your current session that didn't have those types in it. Perhaps another powershell module that loads an older version of YamlDotNet?

If this is still happening in your env and you are running powershell version 6.0+, try the following version:

```powershell
Install-Module -Name powershell-yaml -AllowPrerelease -Version 0.4.8-rc1 -Force
```

This pre-release loads the YamlDotNet bundled with powershell-yaml in another assembly load context and uses that version.

**Comment by gabriel-samfira** [comment]
Closing this. Feel free to re-open if the issue persists.
