### ISSUE TITLE
powershell-yaml module is down

### ISSUE THREAD

**Issue by suman5488** [cloudbase/powershell-yaml#123]
Hi Team,

We are unable to install the PowerShell module in our machines as it is saying service in unavailable. It seems to be downtime is there on the module. Could you please check into this? Thank you. 

![Uploading image.png…]()

**Comment by gabriel-samfira** [comment]
Hi @suman5488 

The module is hosted on powershell gallery. It seems to be fine. Perhaps powershell gallery had a temporary issue?


![Screenshot from 2024-04-04 09-58-30](https://github.com/cloudbase/powershell-yaml/assets/903160/7ca2f58a-f2db-4661-92c6-91814e204467)

Feel free to reopen this if you still encounter errors with complete output.
