### ISSUE TITLE
Powershell-Yaml incorrectly errors on duplicate key

### ISSUE THREAD

**Issue by derekwbrown** [cloudbase/powershell-yaml#124]
I have the latest powershell-yaml installed.
When reading https://github.com/DataDog/datadog-agent/blob/main/.gitlab-ci.yml

powershell-yaml throws a duplicate key error.
This file is properly parsed by gitlab, yamllint.com, etc.

**Comment by gabriel-samfira** [comment]
Hi @derekwbrown 

Try passing in the `-UseMergingParser` as an argument to `ConvertFrom-Yaml`

**Comment by derekwbrown** [comment]
That did indeed work.  Thanks!
