### ISSUE TITLE
Add `SerializationOptions` enum value `SupressNullValuedProperties` / enable the option to not output null values

### ISSUE THREAD

**Issue by JohnLBevan** [cloudbase/powershell-yaml#129]
Today I can run `@{one=1;two=$null} | ConvertTo-Yaml` producing the below output:

```
one: 1
two:
```

It would be good to have the ability to prevent the output of fields with null values, so callers can choose to toggle this behaviour where their inputs contain properties with null values instead of simply not containing those properties.

Desired behaviour:  `@{one=1;two=$null} | ConvertTo-Yaml -Options SupressNullValuedProperties` would produce the output:

```
one: 1
```

**Comment by gabriel-samfira** [comment]
Hi @JohnLBevan 

I opened a PR here:
  * https://github.com/cloudbase/powershell-yaml/pull/137

Is this what you had in mind?

**Comment by JohnLBevan** [comment]
That's awesome / exactly what I was after; thank-you @gabriel-samfira
