### ISSUE TITLE
New Version

### ISSUE THREAD

**Issue by Dargmuesli** [cloudbase/powershell-yaml#14]
Hey!

I would really like to see the latest changes in a new version of powershell-yaml on **PowerShellGallery** and **GitHub releases**.
When do you think are you going to release the next version?

**Comment by gabriel-samfira** [comment]
Many apologies for the late reply. I have published the new version in the powershell gallery:

https://www.powershellgallery.com/packages/powershell-yaml/0.3.1

Cheers!
