### ISSUE TITLE
Parsing Int32 despite non-int characters

### ISSUE THREAD

**Issue by Arokha** [cloudbase/powershell-yaml#145]
`2018+` is parsed into an Int32, which seems unusual. I'd imagine at the very least that discarding a non-whitespace character from the yaml is a bug, instead of throwing on something that can't be unambiguously interpreted.

```
> ("2018+" | ConvertFrom-Yaml).GetType().Name
Int32
```

[The YAML spec](https://yaml.org/spec/1.2.2/) has some example schema (schemas? schemae??), all of which seem that they would interpret the above as a string instead of a number given the regex provided in-spec for integers: `0 | -? [1-9] [0-9]*`

I tested two other popular parser implementations:
`yaml` (TypeScript), parses as string
`pyyaml` (Python), parses as string

Would this be something that could be altered? Or is this a YamlDotNet thing?

**Comment by gabriel-samfira** [comment]
Hi @Arokha 

Marrying C#/Powershell and Yaml is fun :melting_face: .

Would you mind testing out #146 and see if that fixes the issue you're seeing?
