### ISSUE TITLE
Add a flag to output a single line in `ConvertTo-YAML`.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [cloudbase/powershell-yaml#147]
#### **Suggestion**

Sometimes, I want the YAML to be a single line, because some input forms solely permit that.

#### **Cuurent Status**

The current documentation doesn't indicate a way to accomplish this:

1.	```PS1
	(Get-Help -Name 'ConvertTo-YAML').syntax.syntaxItem.parameter | Format-List
	```
	
1.	<blockquote>

	```YAML
	name             : Data
	required         : false
	pipelineInput    : true (ByValue)
	isDynamic        : false
	globbing         : false
	parameterSetName : (All)
	parameterValue   : Object
	type             : @{name=Object}
	position         : 0
	aliases          : None
	
	name             : OutFile
	required         : false
	pipelineInput    : false
	isDynamic        : false
	globbing         : false
	parameterSetName : (All)
	parameterValue   : string
	type             : @{name=string}
	position         : Named
	aliases          : None
	
	name             : JsonCompatible
	required         : false
	pipelineInput    : false
	isDynamic        : false
	globbing         : false
	parameterSetName : NoOptions
	type             : @{name=switch}
	position         : Named
	aliases          : None
	
	name             : KeepArray
	required         : false
	pipelineInput    : false
	isDynamic        : false
	globbing         : false
	parameterSetName : (All)
	type             : @{name=switch}
	position         : Named
	aliases          : None
	
	name             : Force
	required         : false
	pipelineInput    : false
	isDynamic        : false
	globbing         : false
	parameterSetName : (All)
	type             : @{name=switch}
	position         : Named
	aliases          : None
	
	name             : Data
	required         : false
	pipelineInput    : true (ByValue)
	isDynamic        : false
	globbing         : false
	parameterSetName : (All)
	parameterValue   : Object
	type             : @{name=Object}
	position         : 0
	aliases          : None
	
	name             : OutFile
	required         : false
	pipelineInput    : false
	isDynamic        : false
	globbing         : false
	parameterSetName : (All)
	parameterValue   : string
	type             : @{name=string}
	position         : Named
	aliases          : None
	
	name                : Options
	required            : false
	pipelineInput       : false
	isDynamic           : false
	globbing            : false
	parameterSetName    : Options
	parameterValue      : SerializationOptions
	type                : @{name=SerializationOptions}
	position            : Named
	aliases             : None
	parameterValueGroup : @{parameterValue=System.Object[]}
	
	name             : KeepArray
	required         : false
	pipelineInput    : false
	isDynamic        : false
	globbing         : false
	parameterSetName : (All)
	type             : @{name=switch}
	position         : Named
	aliases          : None
	
	name             : Force
	required         : false
	pipelineInput    : false
	isDynamic        : false
	globbing         : false
	parameterSetName : (All)
	type             : @{name=switch}
	position         : Named
	aliases          : None
	```

	</blockquote>

**Comment by gabriel-samfira** [comment]
Could you give an example of what you mean by having the output as a single line?

**Comment by RokeJulianLockhart** [comment]
> https://github.com/cloudbase/powershell-yaml/issues/147#issuecomment-2430420405

@gabriel-samfira, https://stackoverflow.com/revisions/67645180/2#:~:text=networkMapping:%20%7B'test_net_1':%20%7B'external':%20true%7D%2C%20'test_net_2':%20%7B'external':%20true%7D%2C%20'test_net_3':%20%7B'external':%20true%7D%7D provides an example:

> ```YAML
> networkMapping: {'test_net_1': {'external': true}, 'test_net_2': {'external': true}, 'test_net_3': {'external': true}}
> ```

**Comment by skycommand** [comment]
@RokeJulianLockhart That's because your PowerShell command is not well-formed.

The correct command is this:

```PowerShell
$TestYaml = "networkMapping: {'test_net_1': {'external': true}, 'test_net_2': {'external': true}, 'test_net_3': {'external': true}}" | ConvertFrom-Yaml
```

Now you can inspect the resulting object:

```PowerShell
$TestYaml
```
```Output
Name                           Value
----                           -----
networkMapping                 {[test_net_3, System.Collections.Hashtable], [test_net_2, System.Collections.Hashtable], [test_net_1, System.Collections.Hashtable]}
```
```PowerShell
$TestYaml.networkMapping
```
```Output
Name                           Value
----                           -----
test_net_3                     {[external, True]}
test_net_2                     {[external, True]}
test_net_1                     {[external, True]}
```

**Comment by RokeJulianLockhart** [comment]
Yeah, sorry. That was stupid of me.

**Comment by gabriel-samfira** [comment]
That's okay @RokeJulianLockhart ! Happened to me more than once. Glad things got sorted out. Closing this bug.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/cloudbase/powershell-yaml/issues/147#issuecomment-2430907996

@gabriel-samfira, the big hasn't been solved! That was an aside. This bug requests the ability to output a single line. That still isn't possible.

**Comment by gabriel-samfira** [comment]
Have you tried the `-JsonCompatible` flag? It will output json in one line. Jdon being a subset of yaml, you should then be able to parse it with any other library.

**Comment by RokeJulianLockhart** [comment]
@gabriel-samfira, thanks. However, having it in one line merely because it's JSON-compatible, instead of prettified like usual, doesn't seem to make much sense.

Irrespective, I want to use YAML because it's more readable, even on a single line. Outputting JSON-compatible YAML rather nullifies that.

**Comment by gabriel-samfira** [comment]
So, this example:

```powershell
$TestYaml = "networkMapping: {"test_net_1": {"external": true}, "test_net_2": {"external": true}, "test_net_3": {"external": true}}"
```

is equivalent to:

```powershell
$TestYaml = '{"networkMapping": {"test_net_1": {"external": true}, "test_net_2": {"external": true}, "test_net_3": {"external": true}}}'
```

In your example, you essentially have a JSON assigned to `networkMapping`. The only thing I added was an opening and closing bracket. And quotes around `networkMapping`. The rest is identical.

There is no flow style in yaml that gives you a one liner from a data structure that has nested data structures like arrays, maps, etc. Not unless you use json which allows you to have one line. YAML depends on newlines and indents if you want actual yaml. The only places where it doesn't is where you use JSON (which is a subset of yaml).

As an example, here is how python does it. First, with `default_flow_style=False`. This will output YAML:

```python
# With default_flow_style=False
>>> import yaml
>>> data = {"a": [1, 2, 3], "b": {"c": 7}}
>>> print(yaml.dump(data, default_flow_style=False))
a:
- 1
- 2
- 3
b:
  c: 7
```

Now let's try with `default_flow_style=True`:

```python
>>> import yaml
>>> data = {"a": [1, 2, 3], "b": {"c": 7}}
>>> print(yaml.dump(data,default_flow_style=True))
{a: [1, 2, 3], b: {c: 7}}

>>> 
```

We essentially got a JSON.

**Comment by gabriel-samfira** [comment]
Don't get me wrong, I am willing to add a flag to enable the `Flow` style instead of the `Block` style, but I am not sure it adds much value. Lt me know if you really need it and I can add it in the next round of updates.

**Comment by gabriel-samfira** [comment]
See if https://github.com/cloudbase/powershell-yaml/pull/148 suits your needs. It's still a WiP because I also need to write tests, but it should do what you need.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/cloudbase/powershell-yaml/issues/147#issuecomment-2431850520

Many thanks, @gabriel-samfira. I'm no expert at YAML, so I'll acquiesce - your explanation at https://github.com/cloudbase/powershell-yaml/issues/147#issuecomment-2431765362 is fairly comprehensive.

**Comment by gabriel-samfira** [comment]
No worries! I usually add features when they make sense. If nothing else, flow style is useful when used in sequences, as it makes the yaml more compact. If we add flow for sequences, it makes sense to add for mappings as well. So the `mastet` branch has both now.

I need to write some tests and release a new version on PowerShell gallery.
