### ISSUE TITLE
Atom values obtained from Write-Output are incorrectly encoded

### ISSUE THREAD

**Issue by SpecterShell** [cloudbase/powershell-yaml#157]
`ConvertTo-Yaml` is broken in the latest version (v0.4.8) when serializing a hashtable with atom values obtained from Write-Output. It is critical as values may be obtained from the functions that use `Write-Output` rather than `return` to return values.

For example, when assigning with Write-Output:
```PowerShell
[ordered]@{a = Write-Output 'string'; b = Write-Output 1; c = Write-Output @{nested = $true}} | ConvertTo-Yaml
```
```
a:
  Length: 6
b: {}
c:
  nested: true
```
the string and the number were incorrectly encoded.

while without Write-Output:
```PowerShell
[ordered]@{a = 'string'; b = 1; c = @{nested = $true}} | ConvertTo-Yaml
```
```
a: string
b: 1
c:
  nested: true
```
the values were correctly encoded.

**Comment by gabriel-samfira** [comment]
Interesting. Will have a look this evening and push a fix.

**Comment by gabriel-samfira** [comment]
Will also add a test case for this. Does this happen if you generate a variable from write-oitput and use that variable inside the hashtable before sending it to ConvertTo-Yaml?

**Comment by SpecterShell** [comment]
> Will also add a test case for this. Does this happen if you generate a variable from write-output and use that variable inside the hashtable before sending it to ConvertTo-Yaml?

Yes

```PowerShell
$a = Write-Output 'test'
@{a = $a} | ConvertTo-Yaml
```
```
a:
  Length: 4
```

> Does this happen if you pass the hashtable as an argument to ConvertTo-Yaml or does it happen only when piping?

Yes

```PowerShell
ConvertTo-Yaml @{a = Write-Output 'test'}
```
```
a:
  Length: 4
```

**Comment by gabriel-samfira** [comment]
One last test. What is the result of:

```powershell
ConvertTo-Yaml @{a = (Write-Output 'test')}
```

Note the parentheses around the Write-Output command.

**Comment by SpecterShell** [comment]
> ConvertTo-Yaml @{a = (Write-Output 'test')}

The same

```
❯ ConvertTo-Yaml @{a = (Write-Output 'test')}
a:
  Length: 4
```

**Comment by gabriel-samfira** [comment]
PowerShell is dark and full of terrors. I think I may know why this is happening.

This will most likely work if we do an explicit cast like so:

```powershell
ConvertTo-Yaml @{a = [string](Write-Output 'test')}
```

Will have a look once I get to a PC. Thanks for testing.

**Comment by gabriel-samfira** [comment]
Would you mind giving :
  * https://github.com/cloudbase/powershell-yaml/pull/158

a try?

**Comment by gabriel-samfira** [comment]
For context, this issue happened because when we call `Write-Output`, it will wrap whatever we pass to it, in a `PSCustomObject`. The new `PSCustomObject` type converter we are using, will try to list the properties of `PSCustomObjects` and append them to the mapping.

But in this case, we have a primitive type and a string wrapped in a `PSCustomObject`. Strings for example have only one "property", which is the length:

```powershell
PS /> $aString = "test"     
PS /> $aString.psobject.Properties

MemberType      : Property
Value           : 4
IsSettable      : False
IsGettable      : True
TypeNameOfValue : System.Int32
Name            : Length
IsInstance      : True
```

If we pass this simple string to `ConvertTo-Yaml`, then all would be well, but if we wrap it in a `PSCustomObject` like so:

```powershell
$aString = [pscustomobject]"test"
```

then the `PSCustomObject` type converter would be called, and we failed to take into account that some primitives and/or strings may be wrapped. So we recursed through their properties and ended up with the unfortunate behavior you reported. The above PR will attempt to unwrap objects and then serialize them.

**Comment by SpecterShell** [comment]
> Would you mind giving :
> 
>     * [Fix serialization of PSCustomObject wrapped object #158](https://github.com/cloudbase/powershell-yaml/pull/158)
> 
> 
> a try?

Doesn't seem to be fixed. I have ensured it is the modified module has been loaded.

```
❯ @{a = Write-Output 'test'} | ConvertTo-Yaml
a:
  Length: 4
```

**Comment by gabriel-samfira** [comment]
gah! I forgot to add a test case for IDictionary types and only fixed the pscustomobject type. Please pull the latest commit and try again. The test cases [here](https://github.com/cloudbase/powershell-yaml/pull/158/files#diff-d660190b7a179fd7d3183110a9c06e8196038c59ede4e865842ad2e4beae13ffR31-R75) I think should cover everything.

Let me know if it works.

**Comment by SpecterShell** [comment]
> gah! I forgot to add a test case for IDictionary types and only fixed the pscustomobject type. Please pull the latest commit and try again. The test cases [here](https://github.com/cloudbase/powershell-yaml/pull/158/files#diff-d660190b7a179fd7d3183110a9c06e8196038c59ede4e865842ad2e4beae13ffR31-R75) I think should cover everything.
> 
> Let me know if it works.

It works. Thanks for your explanation and fixes!

```
❯ [pscustomobject]@{a = Write-Output 'test'} | ConvertTo-Yaml
a: test

❯ [ordered]@{a = Write-Output 'test'} | ConvertTo-Yaml
a: test

❯ @{a = Write-Output 'test'} | ConvertTo-Yaml
a: test
```

**Comment by gabriel-samfira** [comment]
Thank you for your patience and for testing! I will publish a new release on Monday.

**Comment by gabriel-samfira** [comment]
A new version has been released: https://www.powershellgallery.com/packages/powershell-yaml/0.4.9

A new release has been generated on GitHub: https://github.com/cloudbase/powershell-yaml/releases/tag/v0.4.9

Please test it out and let me know if all is well.

**Comment by SpecterShell** [comment]
> A new version has been released: [powershellgallery.com/packages/powershell-yaml/0.4.9](https://www.powershellgallery.com/packages/powershell-yaml/0.4.9)
> 
> A new release has been generated on GitHub: [`v0.4.9` (release)](https://github.com/cloudbase/powershell-yaml/releases/tag/v0.4.9)
> 
> Please test it out and let me know if all is well.

Works well for me.
