### ISSUE TITLE
Version 0.4.9 and later breaks the use of nested PSCustomObjects

### ISSUE THREAD

**Issue by pareion** [cloudbase/powershell-yaml#168]
**Issue**

When using nested PSCustomObjects powershell-yaml removes the properties of the nested object converting it using `ConvertTo-Yaml`

**Example**

Trying to convert the following object will result in an object losing it's nested properties.

![billede](https://github.com/user-attachments/assets/0521af54-3fd5-4fcf-8afc-916fcb3b39f3)

**Note**
This was possible in version 0.4.8 and was later broken.
![billede](https://github.com/user-attachments/assets/38044cfa-3864-4a00-a7a5-2692e4c8c2d8)

**Bonus**
Adding some unittests for scenarios like these would be a great addition so you don't break already existing features.

**Comment by gabriel-samfira** [comment]
Fix proposed here: https://github.com/cloudbase/powershell-yaml/pull/169

Please test and let me know if it works for you.

**Comment by pareion** [comment]
> Fix proposed here: #169
> 
> Please test and let me know if it works for you.

Works as expected now. Good job. 👍

**Comment by pareion** [comment]
> Hi @pareion
> 
> There are tests for PScustomObjects, but when they are nested within other PSCustomObjects, which in turn are set on a powershell class. I did not think to add one for the case where they are nested within hashtables. Clearly an oversight on my part which will be addressed in a PR soon, along with a fix.
> 
> Also, feel free to send a PR with more test cases. While I try to think of as many test cases as I can, I will inevitably miss some. Luckily, we have a huge community (apparently we get 2.5 million downloads each month on powershell gallery) that can always chip in and help out with additional code, time, testing, etc. Let me know if I can help get you started with proposing a PR for additional tests (completely optional of course).

I'll go through our repos and see if we have some other use cases other than the above mentioned case and let you know. 👍

**Comment by pareion** [comment]
@gabriel-samfira 

Hey again,

Feel free to close the issue when you see fit.

A did a quick glance through our repos and looks like we're primarily working with PSCustomObjects, strings, arrays and booleans. 

I found our most complex objects and made two examples of them (and removed most properties and sanitized) here:

```
$a = [PSCustomObject]@{
    a1 = "a"
    a2 = [PSCustomObject]@{
      "a1" = "a"
      a2 = [PSCustomObject]@{
        a1 = [PSCustomObject]@{
          "a1" = "a"
          a2 = [PSCustomObject]@{
            a1 = "a"
          }
          a3 = [ordered]@{
            a1 = @("a", "b")
          }
          a4 = @("a", "b")
        }
      }
      a3 = @(
        [PSCustomObject]@{
          a1 = "a"
          a2 = $False
        }
      )
    }
  }
```

```
$b = [PSCustomObject]@{
  b1 = "b"
  b2 = [PSCustomObject]@{
    b1 = "b"
    b2 = [PSCustomObject]@{
      "b" = "b"
    }
  }
  b3 = [ordered]@{
      b1 = @("b1", "b2")
    }
  b4 = $True
  b5 = [PSCustomObject]@{
      b = "b"
    }
  }
```

**Comment by gabriel-samfira** [comment]
This is great. I will add them to the tests. I will close this issue when we release a new version, in case someone else hits the same bug and wants to report. Thanks for testing and reporting the bug!

**Comment by gabriel-samfira** [comment]
Version 0.4.11 has been released with a fix for this. Hopefully I didn't break anything else :melting_face:
