### ISSUE TITLE
Output objects, not hash tables

### ISSUE THREAD

**Issue by felixfbecker** [cloudbase/powershell-yaml#18]
`ConvertFrom-Json` outputs objects by default, which are displayed nicer than name/value hashmaps. It only outputs hashmaps if `-AsHashTable` is passed. It would be great if `ConvertFrom-Yaml` worked the same.

**Comment by gabriel-samfira** [comment]
Hi,

Thanks for the suggestion! At this point the benefits of this do not justify the amount of work needed to add this. I will add this to the wishlist though.

Thanks!
