### ISSUE TITLE
Publish new version?

### ISSUE THREAD

**Issue by RamblingCookieMonster** [cloudbase/powershell-yaml#25]
Hiyo!

Any chance you could publish a new version to the gallery?  [This line in particular](https://github.com/cloudbase/powershell-yaml/blob/11752d03060cae7f9223fb9aea7f4c837cc3f5e1/powershell-yaml.psm1#L19) would help avoid a bug in a tool I'm using (i.e. previous behavior using psd1 ScriptsToProcess runs in a useless scope given the bug - loading in psm1 will load them in the right scope)

Cheers!

**Comment by gabriel-samfira** [comment]
Sure. Will update in about 2-3 hours. Need to get to a PC.

**Comment by gabriel-samfira** [comment]
Done
