### ISSUE TITLE
Nested Hashtable Error, but not on JSONCompatible

### ISSUE THREAD

**Issue by jadenguy** [cloudbase/powershell-yaml#29]
I have a hash table who's value is another hash table. The deserializer seems to produce different results if you serialize it normally, vs JSON compatible serialization. JSON compatibility seems to be the accurate mode.

```
get-installedmodule *yaml* |select *|fl
$hash = @{x=@{y=1;z=2}}
write-output "input hash inside hash"
$hash

$hash|convertto-yaml -OutFile '.\yaml.yaml' -Force
$yaml = gc .\yaml.yaml 
write-output "converting to yaml in file, getting valid(?) yaml"
$yaml

$results = $yaml|convertFrom-Yaml
write-output "The deserializer doesn't produce the intended output"
 $results

 $hash|convertto-yaml -OutFile '.\yamljson.yaml' -Force -JsonCompatible
 $yamljson = gc .\yamljson.yaml 
 write-output "converting to yaml json in file, getting valid(?) yaml json"
 $yamljson
 write-output "Deserializer seems ok, so probably, yeah"
 $resultsjson = $yamljson|convertFrom-Yaml
 $resultsjson
```

Fun sidenote, if you use anything to prettify yamljason.yaml, you'll get invalid yaml, which I suppose is consistent with the white-space requirements of yaml, but ruins the human-editability of the JSON file.

**Comment by gabriel-samfira** [comment]
Hi,

Can you replace:
```powershell
$yaml = gc .\yaml.yaml
```

with

```powershell
$yaml = gc -Raw .\yaml.yaml 
```
And try again?

**Comment by gabriel-samfira** [comment]
Apropos, prettifying the json yields the following results:

 ```powershell
PS /tmp> $js = @"
>> {
>>   "x": {
>>     "y": 1,
>>     "z": 2
>>   }
>> }
>> "@
PS /tmp> ConvertFrom-Yaml $js                                                   

Name                           Value
----                           -----
x                              {y, z}

```

**Comment by jadenguy** [comment]
Yup, sorry, didn't even think of that. The -raw fixed both issues.

**Comment by gabriel-samfira** [comment]
This comment is just for posterity.

When you do a ```Get-Content``` without the ```-Raw``` flag, the file is read as an array, where the delimiter is the newline character(s). When you pipe an array to a commandlet, it gets read differently then if you pass the same object as a parameter.

Even if passed in as an argument, it is essentially a different object then the raw text  you really want to convert.
