### ISSUE TITLE
PowerShell Gallery

### ISSUE THREAD

**Issue by flaksirus** [cloudbase/powershell-yaml#3]
Hi, what about to push your project to PowerShell Gallery?

https://www.powershellgallery.com/

Any way I did it for now https://www.powershellgallery.com/packages/powershell-yaml/0.1

I will remove it by first ask.

**Comment by gabriel-samfira** [comment]
Hi flaksirus,

I know it's late, but yes, we would like to push this to the powershell gallery ourselves. We want to do regular updates of this as bugs get fixed.

Thank you for pushing it into the gallery!

Cheers!

**Comment by flaksirus** [comment]
Hi Gabriel,

Ok, I have removed it now (as a package it would take some time for the
system), but can you say when you are going to publish it yourself? I have
use it a lot for my CI/CD scripts and it wouldn't be good for them...
If there would be any problems with publishing please feel free to contact
me and together we will try to find some solution with suppurt of gallery.

Best regards,
Ruslan


2017-04-12 15:28 GMT+03:00 Gabriel <notifications@github.com>:

**Comment by gabriel-samfira** [comment]
It looks like the name powershell-yaml is still reserved by you. I get the following error while publishing:

```powershell
Publish-PSArtifactUtility : Failed to publish module 'powershell-yaml': 'Failed to process request. 'The specified API key belongs to a user who is not authorized to make changes to this item. The item might have been unlisted,
but the name is still reserved by the original owner.'.
The remote server returned an error: (403) Forbidden..
'.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:1227 char:17
+                 Publish-PSArtifactUtility -PSModuleInfo $moduleInfo `
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : FailedToPublishTheModule,Publish-PSArtifactUtility
```

**Comment by flaksirus** [comment]
Ok, I get it, by their rules I can't really remove it myself so I've mailed
to support about this issue. I will contact you after respond from them.

Sorry for this issue...



2017-04-13 21:11 GMT+03:00 Gabriel <notifications@github.com>:

**Comment by gabriel-samfira** [comment]
No worries! Get back to me as soon as it gets removed, and I'll upload it again ASAP :)

**Comment by flaksirus** [comment]
Ok, I get an answer from suppurt and we can't remove package (thats sounds
reasonable for packages system). But we can (and should) change owner of
package, first of all I need invite you (or your organisations account) to
become a co-owner. Then you can request to remove me from package owner
list.
So, I need your account name :)


2017-04-14 0:10 GMT+03:00 Gabriel <notifications@github.com>:

**Comment by alexpilotti** [comment]
@flaksirus our account on the powershell gallery is named "cloudbase"

Thanks!

**Comment by flaksirus** [comment]
Done, I've invited you.


2017-04-15 21:38 GMT+03:00 Alessandro Pilotti <notifications@github.com>:

**Comment by gabriel-samfira** [comment]
It worked. Managed to push the module. Thanks!
