### ISSUE TITLE
Update YamlDotNet.dll

### ISSUE THREAD

**Issue by raandree** [cloudbase/powershell-yaml#31]
There have been quite some releases of YamlDotNet. Can you update the DLL, please? There are no specific issues with the current one but there has been quite some bug fixing in the repo and also some interesting new features like .net Core support.

**Comment by gabriel-samfira** [comment]
Hi,

I will look into it. FYI, the current DLLs work on .net Core :-). This module was born when we were looking for an alternative to ConvertTo-Json for Nano server (it didn't have it in the beginning), back when Nano server still looked like it would make it to bare metal/VMs.

**Comment by gabriel-samfira** [comment]
I currently do not have the time to update the module to work with latest YamlDotNet, which have switched to ```SerializerBuilder``` to set serialization options. But will try to allocate some time next week.

Left some comments on your PR though.

**Comment by gabriel-samfira** [comment]
Hi @raandree 

The PR: https://github.com/cloudbase/powershell-yaml/pull/41

updates the ```YamlDotNet``` assemblies, but the behavior of the RoundTrip serializer might have changed. I remember you had a need to use it. Would you mind taking it for a spin, and let us know if it works for you. If it does, I will merge and release a new version.

**Comment by gabriel-samfira** [comment]
If you have no objections to that PR by Monday, I will merge it, and release a new version. Please leave any comments on the PR, until that time.

**Comment by gabriel-samfira** [comment]
Fixed by: https://github.com/cloudbase/powershell-yaml/pull/41
