### ISSUE TITLE
Indent array values

### ISSUE THREAD

**Issue by Ash258** [cloudbase/powershell-yaml#32]
Is there any way to indent array values with 2 spaces instead of staying at same level? If no could there be option for it?

Example: 

`@{notes = @('some', 'notes', 'as array')} | ConvertTo-Yaml`

Actual:

```yaml
notes:
- some
- notes
- as array
```
Desired:

```yaml
notes:
  - some
  - notes
  - as array
```

**Comment by gabriel-samfira** [comment]
Hi @Ash258 

This seems to be a particularity of YamlDotNet. Powershell-yaml is simply a wrapper on top of YamlDotNet. I am planning on some updates next week and will look into this. They may have implemented prettier indentation of lists, so if they have, it should just port over. No promises though.

Cheers
