### ISSUE TITLE
powershell-yaml parsed 0x* format as String.

### ISSUE THREAD

**Issue by Elderry** [cloudbase/powershell-yaml#34]
Just a proposal, it may be better parsed as an integer, as what PowerShell do.

**Comment by gabriel-samfira** [comment]
YamlDotNet has dificulty parsing ```0x``` prefixed numbers from what I see. It handles hexadecimal numbers fine, as long as they don't have the ```0x``` prefix.

If you expect a hex number and wish to cast it to ```int32```, a workaround would be to do something like:

```powershell
[int]$val = "0x1A"
```

If you feel like this is something that is absolutely needed in your project, and have the time to implement it, I'd be happy to review a pull request that attempts to add this.
