### ISSUE TITLE
Continuous integration

### ISSUE THREAD

**Issue by nohwnd** [cloudbase/powershell-yaml#42]
AppVeyor and TravisCI provide great services that can get your module tested on PowerShell 4+ and Core (on Linux and MacOS) for free. 

Would you accept a PR for the CI setup?

**Comment by gabriel-samfira** [comment]
The issue with most out of the box CI systems is that they require ridiculous access levels to your project, which is something we are not comfortable with to be honest.

There are currently very few PRs being proposed to justify a ci, so I usually run the tests on a proposed branch before I merge.

If there will be increased activity, we can reconsider this. We have a bunch of CIs we run ourselved for various projects, we can plug this project in as well.
