### ISSUE TITLE
Replace Confirm-Equality with a tested solution

### ISSUE THREAD

**Issue by nohwnd** [cloudbase/powershell-yaml#43]
`Confirm-Equality` is not a good basis for your tests. This is not your fault, it's just that comparing artbitrary values in PowerShell is complicated. 🙂 There are no tests for it and it's easy to trick it into being wrong. Here is one example that returns `$true`: 
```
Confirm-Equality -got 1 -expected 1,2,3
```
PowerShell `-eq`  does not work the same way `==` in C# does, and so the first `if` in `Compare-Equality` gives you unexpected result.

I wrote [a module](https://github.com/nohwnd/Assert) that compares objects by structure and that has [600+ of tests](https://ci.appveyor.com/project/nohwnd/assertions/builds/21020671/job/fpj69ph33wf5hhm2). By default it does equivalency checks (less strict), but can be configured to do equality (more strict) as well.

Would you accept PR that would move the tests to using `Assert`?

**Comment by gabriel-samfira** [comment]
Sure! Feel free to propose any PR you feel will improve the codebase, and we can discuss it :-)

**Comment by nohwnd** [comment]
Discussing the change is what I am doing here. I don’t want to implement it just to be told that this is not a direction you wish to take :) (like with the CI, but I totally respect your decision :) )


Jakub Jareš

.NET, Pester, PowerShell
t 00420603800578<tel:00420603800578>
e me@jakubjares.com<mailto:me@jakubjares.com>
t @nohwnd

23. 2. 2019 v 16:03, Gabriel <notifications@github.com<mailto:notifications@github.com>>:


Sure! Feel free to propose any PR you feel will improve the codebase, and we can discuss it :-)

**Comment by gabriel-samfira** [comment]
I was referring to reviewing the PR once it is done :). Any improvement is welcome. If slight changes are needed, that is what the discussion will be focused on :).

I don't feel religious about ```Confirm-Equality```. If you have something better, feel free to propose!
