### ISSUE TITLE
ConvertFrom-Yaml - key named `key` causes weird output when converted back to yaml

### ISSUE THREAD

**Issue by eDISCO** [cloudbase/powershell-yaml#50]
This happens when object with key named `key` are converted back and forth (try below command without the last two `convertfrom` `convertto`)
To reproduce, run:
```powershell
[PSCustomObject]@{keys = @{key = 'YesPlease!'}} | ConvertTo-Yaml | ConvertFrom-Yaml | ConvertTo-Yaml
````
Which gives following output:
```yaml
? &o0
  key: YesPlease!
:
keys: *o0
```

Looking at (https://github.com/aaubry/YamlDotNet/issues/126), it seems like this is related to `DisableAliases` option.
`

This was reproduced both on PS6 on Linux and PS5 on Win10.

**Comment by tricinus** [comment]
I had a similar issue, can reproduce it with this code:
```
$yaml = @{}

$yamlPhases = @{"Dev"="dev1"}

$yaml.Add("lifecycle",$yamlPhases)
$yaml.add("environments",$yamlPhases)

ConvertTo-Yaml $yaml
```
Output:
```
environments: &o0
  Dev: dev1
lifecycle: *o0
```
Seems to output the *o0s when I use the same variable twice in a hash table. With my case I just created a second variable with a different name but same values, and that got rid of the o0:
```
$yaml = @{}

$yamlPhases = @{"Dev"="dev1"}
$yamlPhases1 = @{"Dev"="dev1"}

$yaml.Add("lifecycle",$yamlPhases)
$yaml.add("environments",$yamlPhases1)

ConvertTo-Yaml $yaml
```
Output:
```
environments:
  Dev: dev1
lifecycle:
  Dev: dev1
```

**Comment by gabriel-samfira** [comment]
Would you mind trying the following:

```powershell
ConvertTo-Yaml -Options DisableAliases $yaml
```

and report back?

**Comment by gabriel-samfira** [comment]
Also:

```powershell
$yaml = @{}

$yamlPhases = @{"Dev"="dev1"}
$yamlPhases2 = @{"Dev"="dev1"}

$yaml.Add("lifecycle",$yamlPhases)
$yaml.add("environments",$yamlPhases2)

ConvertTo-Yaml $yaml
```

**Comment by gabriel-samfira** [comment]
Closing this for now. Feel free to reopen if you feel this needs to be addressed in any other way.
