### ISSUE TITLE
Tags Support?

### ISSUE THREAD

**Issue by andrewsav-bt** [cloudbase/powershell-yaml#52]
Hello is there tags support, and if not can it be added? YamlDotNet supports tags.

**Comment by gabriel-samfira** [comment]
Hi,

Apologies for the late reply. Will look into this.

**Comment by gabriel-samfira** [comment]
Would you mind detailing your use case a bit?

**Comment by andrewsav-datacom** [comment]
```chsarp
string test = @"
key: !tag |
      value
      etc
";

var input = new StringReader(test);
var yaml = new YamlStream();
yaml.Load(input);

var mapping = (YamlMappingNode)yaml.Documents[0].RootNode;
mapping["key"].Tag = "!changed";
((YamlScalarNode)mapping["key"]).Value = "hello world!";

StringBuilder sb = new StringBuilder();
StringWriter sw = new StringWriter(sb);
Serializer s = new Serializer();
s.Serialize(sw, mapping);

sb.ToString().Dump();
```

Results in:

```text
key: !changed |-
  hello world!
```

I'd like to achieve the same with powershell-yaml.

**Comment by andrewsav-datacom** [comment]
To be completely honest, I'm not sure what kind of details is missing, so I invite you to clarify that. To me this is quite simple, I was not able to find a way to work with tags at all using powershell-yaml. For example they do not round-trip (that is do not survive ConvertFrom-Yaml ConvertTo-Yaml).

If they are supported, I'd like some examples of how to work with them. If they are not, I'd like them to be supported.

Does this make sense?

**Comment by andrewsav-datacom** [comment]
@gabriel-samfira  An example of tag usage in the wild: https://docs.ansible.com/ansible/latest/user_guide/vault.html#use-encrypt-string-to-create-encrypted-variables-to-embed-in-yaml

**Comment by gabriel-samfira** [comment]
Your examples are great. Will look into adding this to powershell-yaml if possible.

**Comment by ivanakcheurov** [comment]
hi guys, any news on tag support by chance?
