### ISSUE TITLE
Convert*-Json Compatibility

### ISSUE THREAD

**Issue by JustinGrote** [cloudbase/powershell-yaml#55]
I think a major issue preventing wider adoption of this module is that users expect all the same commands and parameters present in ConvertFrom/To-Json, like -Compress and -Depth.

I'd be willing to write the PRs if you'll entertain merging them and considering some potential breaking changes for the next major version, otherwise I'll write it separately as a new module, PowerYAML.

Let me know your thoughts.

**Comment by gabriel-samfira** [comment]
Hi Justin,

In general, pull requests are always welcome. This module receives on average around 20k downloads each day from powershell gallery (around 8 million in total so far). At this point, adding breaking changes will probably make a lot of people unhappy, as most have probably hooked up their CI to pull in the latest version.

That being said, the ```-Depth``` and ```-Compress``` options would be a nice addition. Also, adding new functionality, while preserving the old, is fine. If you are willing to send PRs for something like that, I would be happy to review them.

**Comment by gabriel-samfira** [comment]
Closing this issue. Feel free to reopen if needed.
