### ISSUE TITLE
Failed to serialize a string obtained with Get-Date -Format

### ISSUE THREAD

**Issue by raphaelcardoso** [cloudbase/powershell-yaml#56]
### [1] Running
`ConvertTo-Yaml -Data ([PSCustomObject]@{timestamp = [String](Get-Date -Format 'yyyy-MM-dd')})`

Outputs
`timestamp: 2020-02-10`

### [2] Running
`ConvertTo-Yaml -Data ([PSCustomObject]@{timestamp = (Get-Date -Format 'yyyy-MM-dd').Clone()})`

Outputs
`timestamp: 2020-02-10`

### [3] Running
`ConvertTo-Yaml -Data ([PSCustomObject]@{timestamp = (Get-Date -Format 'yyyy-MM-dd')})`

Outputs (the message is truncated)
```
Exception calling "Serialize" with "2" argument(s): "Too much recursion when traversing the object graph"
At C:\Program Files\WindowsPowerShell\Modules\powershell-yaml\0.4.1\powershell-yaml.psm1:383 char:13
+             $serializer.Serialize($wrt, $norm)
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : InvalidOperationException

timestamp: &o0
  BaseObject: *o0
  Members:
  - IsGettable: true
    OverloadDefinitions:
    - char Chars(int index) {get;}
    TypeNameOfValue: System.Char
    MemberType: ParameterizedProperty
    Value:
      IsGettable: true
      OverloadDefinitions:
      - char Chars(int index) {get;}
      TypeNameOfValue: System.Char
      MemberType: ParameterizedProperty
```

**Comment by gabriel-samfira** [comment]
Hi @raphaelcardoso,

Apologies for the late reply.

Would you mind trying out the latest commit in the master branch, and see if that works for you?

**Comment by raphaelcardoso** [comment]
Hi @gabriel-samfira,

With the latest commit in the master branch, it's working.

Anyway, just for record, I found that the behavior can be can be reproduced using any string that came from the pipeline, contained in a Hashtable or PSCustomObject.

For example, using any of these commands:
```
ConvertTo-Yaml -Data ([PSCustomObject]@{an_string_from_pipe = ('abc' | % {$_})})
ConvertTo-Yaml -Data (@{an_string_from_pipe = ('abc' | % {$_})})
ConvertTo-Yaml -Data ([ordered]@{an_string_from_pipe = ('abc' | % {$_})})
```

Your fix solved them all.

Thank you.

**Comment by gabriel-samfira** [comment]
Great! Will do a release soon. Closing this issue.
