### ISSUE TITLE
Analyser-style capability

### ISSUE THREAD

**Issue by ShadowXVII** [cloudbase/powershell-yaml#59]
It would be useful to have some simple syntax validation functions for just checking specific .yml files are valid.

Similar to https://github.com/PowerShell/PSScriptAnalyzer . Could expand to linting later?

**Comment by gabriel-samfira** [comment]
Hi @ShadowXVII,

Powershell-yaml uses ```YamlDotNet``` to directly deserialize yaml documents. It should be possible to create functions to help validate yaml documents, but it would be a non trivial addition. At this point I do not have the bandwidth to do it. If you are willing to have a go at it, I would be happy to review any PRs.

Feel free to reopen this issue if you feel you would like to tackle this feature.

Thanks!
