### ISSUE TITLE
Serialize Yaml Object

### ISSUE THREAD

**Issue by vineetbindal** [cloudbase/powershell-yaml#60]
Can we get support to serialize Powersell Objects into Yaml files?

**Comment by gabriel-samfira** [comment]
Hi @vineetbindal 

Do you mean something like the ```-OutFile``` option of ```ConvertTo-Yaml```?

https://github.com/cloudbase/powershell-yaml/blob/master/powershell-yaml.psm1#L349

**Comment by vineetbindal** [comment]
@gabriel-samfira yes Thank you. Is there something which can read a file and convert it to Yaml PS object too? currently I am doing this
`[string[]]$fileContent = Get-Content "input\config.yml"
$content = ''
foreach ($line in $fileContent) { $content = $content + "`n" + $line }
$yaml = ConvertFrom-YAML $content`

**Comment by gabriel-samfira** [comment]
I think you can just use:

```powershell
$obj = ConvertFrom-Yaml (Get-Content -Raw "input\config.yml")
```
