### ISSUE TITLE
Problems with round-tripping.

### ISSUE THREAD

**Issue by chidozieononiwu** [cloudbase/powershell-yaml#61]
The powershell-yaml module is quite very effective, however there are some tiny things that go missing when converting from yaml to PSObject and back to yaml.

1. Comments are missing.
i.e. Comments starting with `#`

2. Values with quotes don't convert well
`TargetFolder: '.'` becomes `TargetFolder: .`
`versionSpec: '3.6'` becomes `versionSpec: "3.6"`

**Comment by gabriel-samfira** [comment]
Hi @chidozieononiwu 

1. Comments are currently discarded when deserializing. Theoretically, they could be preserved, but that is not a feature I currently have time to implement. If you'd like to have a go at it, I would be happy to review a PR.

2. Unfortunately, the yaml spec is very forgiving, in the sense that strings may be quoted by single quotes, double quotes or no quotes. In general, it is advised to use tags to indicate the type, but unfortunately we don't (yet) support tags. What we have done, was to try and disambiguate the values when we serialize to yaml, so as to retain the type when deserializing again.

The dot is considered a string even without quotes. In the absence of tags, integers and floats may loose their type when serializing and deserializing and that is why we add double quotes. We do not preserve the quotation type however, as that has no bearing on functionality. This is a limitation in any yaml parser (if tags are not present).

To preserve comments, quotes and to enable round-tripping, this module will need to define its own types and keep track of scalars and their tags/comments. This is not something I currently have time for, but is a feature I would like to implement at some point. Currently, ```powershell-yaml``` will only deserialize in existing powershell basic types (hashtables, arrays, strings, floats, etc), and that makes it difficult to preserve any metadata about the scalars.
