### ISSUE TITLE
Sorting imported YAML breaks ConvertTo-YAML

### ISSUE THREAD

**Issue by bcdady** [cloudbase/powershell-yaml#63]
I want to import from an existing YAML file, modify, and then write a new/replacement YAML file, ideally in the same order / layout as it was imported. My use/test case is on PowerShell 7 (Core), running on MacOS. So far, all other expected functionality of powershell-yaml is excellent.

Currently, I can import (ConvertFrom-YAML), but it doesn't seem the -Ordered parameter works to alphabetically order the Keys/Names.

If I sort the imported object, and then use ConvertTo-Yaml, the results are NOT valid YAML.
Example as PowerShell object:
```powershell
----                           -----
Name                           Value
autoscaling                    {maxReplicas, enable, minReplicas}
deployment                     {replicaCount}
inboundTraffic                 {cname}
initContainers                 {rectify}
```

Example after `ConvertTo-Yaml -Data ($values | sort)`:
```yaml
- ""
- ""
- '----                           -----'
- Name                           Value
- autoscaling                    {maxReplicas, enable, minReplicas}
- deployment                     {replicaCount}
- inboundTraffic                 {cname}
- initContainers                 {rectify}
```

**Comment by olljanat** [comment]
It looks to be that even test cases in here does sorting https://github.com/cloudbase/powershell-yaml/blob/03663c66e57ce2d0422077dc073bdb92e4d374b0/Tests/powershell-yaml.Tests.ps1#L125-L137

@gabriel-samfira I can see that you have added those test on https://github.com/cloudbase/powershell-yaml/commit/db5a680f6c006c6cc70e830fc91d9f16ce55e837
Do you have ideas what we can do for this? I think that we should modify tests on way that there is data which are not in order, then remove sort commands from them and figure out how to still get expected result.

**Comment by mstjernfelt** [comment]
I got it to output the same yaml by adding -ordered in the ConvertTo-Yaml

```
$ymlContent = Get-Content $ymlPath | ConvertFrom-Yaml -Ordered
$ymlContent | ConvertTo-Yaml | Out-File $outPath
```

**Comment by gabriel-samfira** [comment]
Hi folks,

My apologies for taking so long to respond!

This should be fixed by the ```-Ordered``` flag passed to ```ConvertFrom-Yaml```, as @mstjernfelt  mentioned. If it still doesn't work for you, please re-open this issue with a sample yaml.
