### ISSUE TITLE
Float formatting not possible ?

### ISSUE THREAD

**Issue by frank-afa** [cloudbase/powershell-yaml#66]
When Reading a YAML file which contains i. ex. :  "version: 2.9" and convert it , the output is 2.8999999999999999.
Even when setting the value to 2.9 and then do converting to yaml, it gives 2.8999999999999999 again.
Any ideas ?

Thx in advance
Frank

**Comment by Tem-Dev** [comment]
Mine seems to do the exact opposite. Pic contains my used commands, you could try those if you don't need long fractions.
![image](https://user-images.githubusercontent.com/45674588/91670963-af426180-eb22-11ea-86a0-e3eefbd77050.png)
Also please specify the commands you use, could help people reproduce the problem ;)
Good Luck!

**Comment by necoras** [comment]
Is there any movement on this? I'm seeing the same behavior. The conversion happens on the ConvertTo-Yaml step. If you inspect the object that ConvertFrom-Yaml creates the value is preserved until it's converted back to a yaml file.

**Comment by gabriel-samfira** [comment]
Hi folks,

My apologies for the late reply!

Could you please try the latest commit and see if this happens? On my system the result is:

```powershell
PS /tmp> $a = "version: 2.9"        
PS /tmp> cfy $a             

Name                           Value
----                           -----
version                        2.9

PS /tmp> cfy $a | cty               
version: 2.9
```

When reading from a file:

```powershell
PS /tmp> type ./test.yaml             
version: 2.9
PS /tmp> cfy (gc -raw test.yaml)      

Name                           Value
----                           -----
version                        2.9

PS /tmp> cfy (gc -raw test.yaml) | cty
version: 2.9
```

Also, when reading from file, please use:

```powershell
ConvertFrom-Yaml (Get-Content -Raw data.yaml)
```

The ```-Raw``` flag will give a raw string to ```ConvertFrom-Yaml``` as opposed to an array of lines encoded in a powershell object.

Feel free to re-open this issue if it still happens.
