### ISSUE TITLE
$null values not encoded as JSON null

### ISSUE THREAD

**Issue by nu11ptr** [cloudbase/powershell-yaml#67]
### Steps to reproduce

```Powershell
@{test=$null} | ConvertTo-Yaml
```

### Expected output
```Powershell
test: null
```

### Actual output
```Powershell
test:
```

**Comment by ArmaanMcleod** [comment]
@nu11ptr If you specify `JsonCompatible` option it works:

```pwsh
PS C:\> @{test=$null} | ConvertTo-Yaml -Options ([YamlDotNet.Serialization.SerializationOptions]::JsonCompatible)
{"test": null}
```

**Comment by gabriel-samfira** [comment]
This is how ```YamlDotNet``` serializes ```$null```. As @ArmaanMcleod mentioned, when using ```-JsonCompatible``` it should output the ```JSON``` null value.
