### ISSUE TITLE
Error - StringQuotingEmitter

### ISSUE THREAD

**Issue by marcossilvestrini** [cloudbase/powershell-yaml#68]
Hi.

I use this module at my company. This is perfect for manipulating models, but whenever I import it into my scripts, I get the message below:

Add-Type: F:\Projetos\yml-to-json\powershell-yaml\powershell-yaml.psm1:312:5
Line |
 312 |      Add-Type -TypeDefinition $stringQuotingEmitterSource -ReferencedA …
     |      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  
     | Cannot add type. The type name 'StringQuotingEmitter' already exists.   

Thks.

**Comment by gabriel-samfira** [comment]
Hi @marcossilvestrini !

My apologies for the late reply!

I've created a PR to fox this here: #103
