### ISSUE TITLE
DateTime values are incorrectly parsed as always DateTimeKind.Local

### ISSUE THREAD

**Issue by amis92** [cloudbase/powershell-yaml#69]
## Problem

DateTime values are incorrectly parsed as always DateTimeKind.Local

https://github.com/cloudbase/powershell-yaml/blob/03663c66e57ce2d0422077dc073bdb92e4d374b0/powershell-yaml.psm1#L86

## Repro

Local kind:

```powershell
([DateTime]::UtcNow | ConvertTo-Yaml | ConvertFrom-Yaml).Kind
Local
```

Not round-trippable:

```powershell
$ts = [DateTime]::SpecifyKind("2020-02-20T20:20Z", [System.DateTimeKind]::Utc)
$ts | ConvertTo-Yaml
$ts | ConvertTo-Yaml | ConvertFrom-Yaml | ConvertTo-Yaml
```

prints (if you're in UTC+0)

```
2020-02-20T21:20:00.0000000Z
2020-02-20T22:20:00.0000000+00:00
```

## Suggested solution

First attempt to TryParse with RoundtripKind (very specific format), then continue to match with current method.

Roundtrip parsing:
```powershell
$ts = [DateTime]::SpecifyKind("2020-02-20T20:20Z", [System.DateTimeKind]::Utc)
$tsout = [datetime]::MinValue
$tss = $ts.ToString("o")
$result = [datetime]::TryParse($tss, $null, [System.Globalization.DateTimeStyles]::RoundtripKind, [ref] $tsout)
```

The `result` should be true.

**Comment by gabriel-samfira** [comment]
Hi @amis92 !

My apologies for not getting back to you earlier!

In hindsight, I should have never tried to parse dates at all, and just return the string and allow the user of the library to decide how they want to parse it.

The latest version does exactly this, except for when the ```!!timestamp``` tag is used. Your suggestion to use ```UTC``` and the ```RoundtripKind``` is great. I will create a PR to default to UTC soon.

**Comment by amis92** [comment]
Happy to see it addressed! I see you're on fire ;) Thanks!

**Comment by gabriel-samfira** [comment]
@amis92 I locked a couple of days to address the embarrassingly long list of unaddressed issues :disappointed_relieved: .  I am hoping to be able to lock a few more days once I finish with my backlog, to attempt to write a (de)serializer which would allow us to finally round-trip....but we'll see how that goes.
