### ISSUE TITLE
Colon inside dictionary throws error

### ISSUE THREAD

**Issue by NPCGundlach** [cloudbase/powershell-yaml#74]
Hi,

Some data I'm working with stores one or more URLs inside dictionaries in a YAML file. Parsing this file throws the following error:
```PowerShell
Ausnahme beim Aufrufen von "Load" mit 1 Argument(en):  "(Line: 1, Col: 8, Idx: 7) - (Line: 1, Col: 13, Idx: 12): While
scanning a plain scalar, find unexpected ':'."
In C:\Program Files\WindowsPowerShell\Modules\powershell-yaml\0.4.2\powershell-yaml.psm1:38 Zeichen:9
+         $yamlStream.Load([YamlDotNet.Core.IParser] $parser)
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : SyntaxErrorException
```
The German part in the beginning say "Exception while calling 'Load' with 1 argument(s)"

Example data:

```yaml
a: {b: https://example.com}
```

According to the [Ansible YAML Docs](https://docs.ansible.com/ansible/latest/reference_appendices/YAMLSyntax.html#gotchas), colons only need to be put in quotes if it's directly followed after whitespace - which is not the case in an URL.  
Note that an URL outside of a dictionary doesn't lead to errors.

**Comment by gabriel-samfira** [comment]
Hi @NPCGundlach 

My apologies for the late reply!

I think this was fixed in a later version of YamlDotNet. With the current version of ```powershell-yaml```, this does not reproduce anymore.

```powershell
PS /tmp> $a = "a: {b: https://example.com}"
PS /tmp> cfy $a

Name                           Value
----                           -----
a                              {[b, https://example.com]}
```

Feel free to re-open the issue if it still happens to you.
