### ISSUE TITLE
ConvertFrom-Yaml throws when using a YAMl document with only comments

### ISSUE THREAD

**Issue by chrischu** [cloudbase/powershell-yaml#79]
When using ConvertFrom-Yaml on a string like this:
```
# Comment
``` 

I get the following error message:
```
ConvertFrom-Yaml: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
```

In my opinion, this should not fail, but instead just return an empty object.

**Comment by gabriel-samfira** [comment]
After an embarrassingly long time since this was open, I think if this was an issue, it was fixed in the meantime:

```powershell
PS /home/gabriel> $yaml = "# Comment"             
PS /home/gabriel> ConvertFrom-Yaml $yaml 
PS /home/gabriel> $yaml | ConvertFrom-Yaml               
PS /home/gabriel>
```

My apologies to you, and everyone else that opened an issue and never got a response. I'll try to get through as many as possible.
