### ISSUE TITLE
Regional settings influence conversion 

### ISSUE THREAD

**Issue by majkinetor** [cloudbase/powershell-yaml#8]
```powershell
> 'pi: 3.14' | ConvertFrom-Yaml

Name                           Value
----                           -----
pi                             314

> 'pi: 3,14' | ConvertFrom-Yaml

Name                           Value
----                           -----
pi                             3,14


> [System.Globalization.CultureInfo]::CurrentCulture.NumberFormat | % NumberDecimalSeparator    
, 
```

**Comment by majkinetor** [comment]
I guess this is not expected since there is no culture in Powershell, just in conversion to text.

When I add the following in BEGIN section of `ConvertFrom-Yaml` it works as expected:

```
$currentThread = [System.Threading.Thread]::CurrentThread
$culture = [System.Globalization.CultureInfo]::InvariantCulture
$currentThread.CurrentCulture = $culture
$currentThread.CurrentUICulture = $culture
```

I am not sure at this moment if this is correct way to do it tho.

**Comment by gabriel-samfira** [comment]
I apologise for completely forgetting about this.

I made a push that should fix this without hacking the ```CurrentThread``` culture.  Can you try out: 

https://github.com/cloudbase/powershell-yaml/commit/25f0e6d00a34b8d51af1df30cc304fab521639fa

and let me know if it works for you.

**Comment by gabriel-samfira** [comment]
Closing this issue. Feel free to reopen it if it still presents a problem.
