### ISSUE TITLE
Can ConvertFrom-Yaml maintain the source order and processes deeper?

### ISSUE THREAD

**Issue by SteveTinkers** [cloudbase/powershell-yaml#89]
I'm working on a project that writes a configuration file based on some values in a yml.  It works great in Ansible and I'm adapting it to Windows.  

The program is pretty particular about the order of the sections in the config file....
ConvertFrom-Yaml likes to change the order.  Can it be left the same?

Can it process just a little deeper? Some values under profile->rules->exceptions-> are missing...  Could be a  ConvertTo-Json thing, I just noticed it while writing this.

Source YML:
```

"section":
    "value1": "teststring"
    "value2": true
    "group":
        "gv1": true
        "gv2": true

"profile":
    "rules":
        "exceptions":
            "trackers":
                "*,*":
                    "setting": 2
"search":
    "suggest_enabled": true
```

Output JSON
```
{
    "profile":  {
                    "rules":  {
                                  "exceptions":  "System.Collections.Hashtable"
                              }
                },
    "section":  {
                    "value1":  "teststring",
                    "group":  {
                                  "gv2":  true,
                                  "gv1":  true
                              },
                    "value2":  true
                },
    "search":  {
                   "suggest_enabled":  true
               }
}
```

Conversion Powershell Script:
```

```
$ymlfile = (Get-Content -Path ".\test.yml" | ConvertFrom-Yaml)
Set-Content -Path ".\test.json" -Value ($ymlfile | ConvertTo-Json)
```

**Comment by SteveTinkers** [comment]
Ah ha!  Thank you.  I'll mess with this mid next week when I'm back at my fun development station.  

I swear I tried to read the documentation... 😉

**Comment by gabriel-samfira** [comment]
My pleasure! Will close this issue. Feel free to reopen if things don't work.
