### ISSUE TITLE
Support to PowerShell in Constrained Language Mode

### ISSUE THREAD

**Issue by schenardie** [cloudbase/powershell-yaml#98]
Hi there, would be possible to change the PSM1 export-modulemembers to not use * (not supported on constrained language mode) to instead use 

`Export-ModuleMember -Function ConvertFrom-Yaml,ConvertTo-Yaml -Alias cfy,cty`

That would be really helpful for people who run the module controlled environments. 

Thanks

**Comment by gabriel-samfira** [comment]
Hi @schenardie !

I merged #99 which should fix this. I will try to allocate some time to push this to powershell gallery this week. Until then, would you mind using the latest commit?

**Comment by schenardie** [comment]
I can't because every module that is not coming from Gallery cannot be changed after installed (otherwise the hash will change) but I'll wait until you publish. TBH wasn't expecting that quick of a turnaround so thank again.

**Comment by gabriel-samfira** [comment]
New version has been published to the powershell gallery. Sorry for the delay. Give it a shot.

**Comment by schenardie** [comment]
You are a legend. Thanks so much for that.
